<a href="https://colab.research.google.com/github/MikeMNelhams/SkyBroadbandProject/blob/main/SkyBroadbandProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Project Questions

1. **How can we measure the Customer Experience?** 
2. **Are there different clusters of users?**
3. **How does this change over time?** 


---


# NOTE: Saving the google colab will override anybody else's work, so please have a draft file of your work saved externally.

In [2]:
# Package Imports
%tensorflow_version 2.x 

import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
import tensorflow as tf

In [ ]:
# Data Imports
sky_performance_data_url = 'https://raw.githubusercontent.com/MikeMNelhams/SkyBroadbandProject/main/2019-ISP-Broadband-performance-data.csv?token=AOVV27H4MJPUN6CZHEDKK2C7TFCGS'

SPD = pd.read_csv(sky_performance_data_url) # sky_performance_data (SPD)

In [5]:
SPD

       unit_id      ISP Technology  ...  isp_wghts Natweight rural_weight
0       941318   Virgin      Cable  ...   1.000000    0.7180      1.08753
1         1323  Plusnet       FTTC  ...   0.880000       NaN          NaN
2     22074685     KCOM       FTTP  ...   1.000000    0.0016      0.26727
3         1360      Sky      ADSL2  ...   1.633333    6.0001      0.52838
4       813667  Plusnet      ADSL1  ...        NaN    0.0064      0.35144
...        ...      ...        ...  ...        ...       ...          ...
3460   6481369       BT       FTTC  ...   1.566667       NaN          NaN
3461  29247893       BT       FTTC  ...   0.854545       NaN          NaN
3462  25201485       BT       FTTC  ...   0.854545    0.4322      0.50728
3463  29249389       BT       FTTC  ...   0.854545       NaN          NaN
3464  25883373       BT       FTTC  ...   0.671429    0.3975      0.50728

[3465 rows x 78 columns]